from fastapi import APIRouter
from app.api.v1.endpoints import (
    auth, users, warehouses, items, barcodes,
    ledger, purchase_orders, sales_orders, reports, audit, search, settings, documents, operations, costing, analytics, warehouse, procurement, traceability, sync, pricing, sales_analytics, invoicing, ap, manufacturing, replenishment, shipping,
    portal_auth, portal_customer, portal_supplier, payments, general_ledger, notifications, automation, auth_security, advanced_manufacturing, supply_chain, accounting_period, tax_and_currency, fixed_assets, budgeting, forecasting, approval, pricing_v2,
    health, metrics, intercompany, edms, maintenance, vendor_scorecards, reconciliation
)

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["Authentication"])
api_router.include_router(auth_security.router, prefix="/auth/security", tags=["Auth Hardening, MFA & SSO"])
api_router.include_router(portal_auth.router, prefix="/portal/auth", tags=["B2B Portal Authentication"])
api_router.include_router(portal_customer.router, prefix="/portal/customer", tags=["B2B Customer Portal"])
api_router.include_router(portal_supplier.router, prefix="/portal/supplier", tags=["B2B Supplier Portal"])
api_router.include_router(payments.router, prefix="/payments", tags=["Payment Gateway & AR Settlement"])
api_router.include_router(general_ledger.router, prefix="/gl", tags=["General Ledger & Financial Reporting"])
api_router.include_router(reconciliation.router, prefix="/finance/reconciliation", tags=["Subledger Reconciliation & Integrity"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["Notifications & Alerts"])
api_router.include_router(automation.router, prefix="/automation", tags=["Background Automation & Jobs"])
api_router.include_router(users.router, prefix="/users", tags=["Users & RBAC"])
api_router.include_router(warehouses.router, prefix="/warehouses", tags=["Warehouses & Bins"])
api_router.include_router(items.router, prefix="/items", tags=["Item Master Catalog"])
api_router.include_router(barcodes.router, prefix="/barcodes", tags=["Barcodes & Labels"])
api_router.include_router(ledger.router, prefix="/ledger", tags=["Double-Entry Stock Ledger"])
api_router.include_router(manufacturing.router, prefix="/manufacturing", tags=["Manufacturing, BOM & Work Orders"])
api_router.include_router(advanced_manufacturing.router, prefix="/manufacturing/advanced", tags=["Advanced Manufacturing & Routing"])
api_router.include_router(replenishment.router, prefix="/replenishment", tags=["Automated Replenishment & Demand Planning"])
api_router.include_router(shipping.router, prefix="/shipping", tags=["Shipping, Carrier & Fulfillment Integration"])
api_router.include_router(purchase_orders.router, prefix="/purchase-orders", tags=["Purchasing & Goods Receipt"])
api_router.include_router(procurement.router, prefix="/procurement", tags=["Purchasing & Supplier Management 2.0"])
api_router.include_router(vendor_scorecards.router, prefix="/procurement/scorecards", tags=["Supplier Performance & Scorecards"])
api_router.include_router(ap.router, prefix="/ap", tags=["Vendor Accounts Payable & 3-Way Match"])
api_router.include_router(sales_orders.router, prefix="/sales-orders", tags=["Sales & Dispatch"])
api_router.include_router(invoicing.router, prefix="/invoicing", tags=["Invoicing, AR & Payments"])
api_router.include_router(pricing.router, prefix="/pricing", tags=["Pricing & Price Lists"])
api_router.include_router(sales_analytics.router, prefix="/analytics/sales", tags=["Sales Analytics & Margin Intelligence"])
api_router.include_router(reports.router, prefix="/reports", tags=["Reports & Analytics"])
api_router.include_router(audit.router, prefix="/audit", tags=["Audit Trail"])
api_router.include_router(search.router, prefix="/search", tags=["Global Search"])
api_router.include_router(settings.router, prefix="/settings", tags=["System Settings"])
api_router.include_router(documents.router, prefix="/documents", tags=["Business Documents & PDF"])
api_router.include_router(operations.router, prefix="/operations", tags=["Backup, Monitoring & Operations"])
api_router.include_router(costing.router, prefix="/costing", tags=["Inventory Costing & Valuation"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["Advanced Inventory Analytics & Replenishment"])
api_router.include_router(warehouse.router, prefix="/warehouse", tags=["Warehouse Operations & Barcode Workflows"])
api_router.include_router(traceability.router, prefix="/traceability", tags=["Lot, Batch & Serial Traceability"])
api_router.include_router(sync.router, prefix="/sync", tags=["Offline Desktop & Synchronization"])
api_router.include_router(supply_chain.router, prefix="/supply-chain", tags=["Multi-Echelon Supply Chain & Edge Sync"])
api_router.include_router(accounting_period.router, prefix="/gl/periods", tags=["Accounting Periods & Fiscal Year Closing"])
api_router.include_router(tax_and_currency.router, prefix="/finance", tags=["Multi-Currency & Enterprise Tax Engine"])
api_router.include_router(fixed_assets.router, prefix="/finance/assets", tags=["Fixed Assets & Depreciation Engine"])
api_router.include_router(budgeting.router, prefix="/finance/budgets", tags=["Cost Centers & Departmental Budgeting"])
api_router.include_router(forecasting.router, prefix="/replenishment/forecasts", tags=["Demand Forecasting & Statistical Replenishment"])
api_router.include_router(approval.router, prefix="/approvals", tags=["Multi-Level Approvals & Delegation of Authority"])
api_router.include_router(pricing_v2.router, prefix="/pricing/v2", tags=["Dynamic Pricing & Rebate Engine"])
api_router.include_router(health.router, prefix="/health", tags=["Enterprise Health & Diagnostics"])
api_router.include_router(metrics.router, prefix="/metrics", tags=["Prometheus Telemetry"])
api_router.include_router(intercompany.router, prefix="/intercompany", tags=["Multi-Entity Intercompany Trade & Eliminations"])
api_router.include_router(edms.router, prefix="/edms", tags=["Enterprise Document Management & Audit Sign-Off"])
api_router.include_router(maintenance.router, prefix="/maintenance", tags=["Enterprise Preventive Maintenance & Work Orders"])
